---
abstract: 'A proper ODM (Object-Document-Mapper) for MongoDB '
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MongoDBI
requires:
  Carp: 0
  DateTime: 0
  IO::File: 0
  JSON: 0
  Module::Find: 0
  MongoDB: 0
  Moose: 0
  MooseX::Traits: 0
  Scalar::Util: 0
  boolean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MongoDBI
  homepage: http://ana.io/
  repository: http://github.com/alnewkirk/MongoDBI.git
version: 0.0.8
